/*****************************************************************************
*
* Copyright (c) 2000 - 2018, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtMDSCHISMFileFormat.C                           //
// ************************************************************************* //

#include <avtMDSCHISMFileFormat.h>
#include <string>
#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>
#include <avtDatabaseMetaData.h>
#include <DBOptionsAttributes.h>
#include <Expression.h>
#include <InvalidVariableException.h>
#include "FileFormatFavorFactory.h"

#include <vtkCharArray.h>
#include <vtkDoubleArray.h>
#include <vtkFloatArray.h>
#include <vtkIntArray.h>
#include <vtkLongArray.h>
#include <vtkShortArray.h>
#include <vtkUnsignedCharArray.h>
#include <vtkUnsignedIntArray.h>
#include <vtkUnsignedShortArray.h>

#include <vtkCellArray.h>
#include <vtkCellData.h>
#include <vtkCellType.h>
#include <vtkFieldData.h>
#include <vtkInformation.h>
#include <vtkRectilinearGrid.h>
#include <vtkStreamingDemandDrivenPipeline.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>
#include <avtGhostData.h>
#include <DebugStream.h>
using     std::string;


// ****************************************************************************
//  Method: avtMDSCHISMFileFormat constructor
//
//  Programmer: qshu -- generated by xml2avt
//  Creation:   Fri Jul 31 10:54:14 PDT 2020
//
// ****************************************************************************

avtMDSCHISMFileFormat::avtMDSCHISMFileFormat(const char *filename)
    : avtMTMDFileFormat(filename)
{
    // INITIALIZE DATA MEMBERS
	//m_impl.reset(FileFormatFavorFactory::Instance()->CreateInstance("md_nc4"));
}


// ****************************************************************************
//  Method: avtMDSCHISMFileFormat::GetNTimesteps
//
//  Purpose:
//      Tells the rest of the code how many timesteps there are in this file.
//
//  Programmer: qshu -- generated by xml2avt
//  Creation:   Fri Jul 31 10:54:14 PDT 2020
//
// ****************************************************************************

int
avtMDSCHISMFileFormat::GetNTimesteps(void)
{
    return m_impl->GetNTimesteps(m_data_file);
}


// ****************************************************************************
//  Method: avtMDSCHISMFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: qshu -- generated by xml2avt
//  Creation:   Fri Jul 31 10:54:14 PDT 2020
//
// ****************************************************************************

void
avtMDSCHISMFileFormat::FreeUpResources(void)
{
	 m_impl->FreeUpResources();
}


// ****************************************************************************
//  Method: avtMDSCHISMFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: qshu -- generated by xml2avt
//  Creation:   Fri Jul 31 10:54:14 PDT 2020
//
// ****************************************************************************

void
avtMDSCHISMFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md, int timeState)
{
	//
	// CODE TO ADD A MESH
	//
	string meshname = "test_2d";
	//
	// AVT_RECTILINEAR_MESH, AVT_CURVILINEAR_MESH, AVT_UNSTRUCTURED_MESH,
	// AVT_POINT_MESH, AVT_SURFACE_MESH, AVT_UNKNOWN_MESH
	avtMeshType mt = AVT_UNSTRUCTURED_MESH;
	//
	int nblocks = 2;
	int block_origin = 0;
	int spatial_dimension = 2;
	int topological_dimension = 2;
	double *extents = NULL;
	//
	// Here's the call that tells the meta-data object that we have a mesh:
	//
	AddMeshToMetaData(md, meshname, mt, extents, nblocks, block_origin,
		spatial_dimension, topological_dimension);
	//

	//
	// CODE TO ADD A SCALAR VARIABLE
	//
	string mesh_for_this_var = meshname;
	string varname = "elev";
	//
	// AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
	avtCentering cent = AVT_NODECENT;
	//
	//
	// Here's the call that tells the meta-data object that we have a var:
	//
	AddScalarVarToMetaData(md, varname, mesh_for_this_var, cent);
	return;
    m_impl->PopulateDatabaseMetaData(md, this,timeState);
    // CODE TO ADD A MESH
    //
    // string meshname = ...
    //
    // AVT_RECTILINEAR_MESH, AVT_CURVILINEAR_MESH, AVT_UNSTRUCTURED_MESH,
    // AVT_POINT_MESH, AVT_SURFACE_MESH, AVT_UNKNOWN_MESH
    // avtMeshType mt = AVT_RECTILINEAR_MESH;
    //
    // int nblocks = YOU_MUST_DECIDE;
    // int block_origin = 0;
    // int spatial_dimension = 2;
    // int topological_dimension = 2;
    // double *extents = NULL;
    //
    // Here's the call that tells the meta-data object that we have a mesh:
    //
    // AddMeshToMetaData(md, meshname, mt, extents, nblocks, block_origin,
    //                   spatial_dimension, topological_dimension);
    //

    //
    // CODE TO ADD A SCALAR VARIABLE
    //
    // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
    // string varname = ...
    //
    // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
    // avtCentering cent = AVT_NODECENT;
    //
    //
    // Here's the call that tells the meta-data object that we have a var:
    //
    // AddScalarVarToMetaData(md, varname, mesh_for_this_var, cent);
    //

    //
    // CODE TO ADD A VECTOR VARIABLE
    //
    // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
    // string varname = ...
    // int vector_dim = 2;
    //
    // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
    // avtCentering cent = AVT_NODECENT;
    //
    //
    // Here's the call that tells the meta-data object that we have a var:
    //
    // AddVectorVarToMetaData(md, varname, mesh_for_this_var, cent,vector_dim);
    //

    //
    // CODE TO ADD A TENSOR VARIABLE
    //
    // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
    // string varname = ...
    // int tensor_dim = 9;
    //
    // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
    // avtCentering cent = AVT_NODECENT;
    //
    //
    // Here's the call that tells the meta-data object that we have a var:
    //
    // AddTensorVarToMetaData(md, varname, mesh_for_this_var, cent,tensor_dim);
    //

    //
    // CODE TO ADD A MATERIAL
    //
    // string mesh_for_mat = meshname; // ??? -- could be multiple meshes
    // string matname = ...
    // int nmats = ...;
    // vector<string> mnames;
    // for (int i = 0 ; i < nmats ; i++)
    // {
    //     char str[32];
    //     sprintf(str, "mat%d", i);
    //     -- or -- 
    //     strcpy(str, "Aluminum");
    //     mnames.push_back(str);
    // }
    // 
    // Here's the call that tells the meta-data object that we have a mat:
    //
    // AddMaterialToMetaData(md, matname, mesh_for_mat, nmats, mnames);
    //
    //
    // Here's the way to add expressions:
    //Expression momentum_expr;
    //momentum_expr.SetName("momentum");
    //momentum_expr.SetDefinition("{u, v}");
    //momentum_expr.SetType(Expression::VectorMeshVar);
    //md->AddExpression(&momentum_expr);
    //Expression KineticEnergy_expr;
    //KineticEnergy_expr.SetName("KineticEnergy");
    //KineticEnergy_expr.SetDefinition("0.5*(momentum*momentum)/(rho*rho)");
    //KineticEnergy_expr.SetType(Expression::ScalarMeshVar);
    //md->AddExpression(&KineticEnergy_expr);
    //
	
}


// ****************************************************************************
//  Method: avtMDSCHISMFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      timestate   The index of the timestate.  If GetNTimesteps returned
//                  'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain      The index of the domain.  If there are NDomains, this
//                  value is guaranteed to be between 0 and NDomains-1,
//                  regardless of block origin.
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: qshu -- generated by xml2avt
//  Creation:   Fri Jul 31 10:54:14 PDT 2020
//
// ****************************************************************************

vtkDataSet *
avtMDSCHISMFileFormat::GetMesh(int timestate, int domain, const char *meshname)
{
	vtkUnstructuredGrid *uGrid = vtkUnstructuredGrid::New();
	vtkPoints *points = vtkPoints::New();
	points->SetDataType(VTK_DOUBLE);
	debug1 << "start creating mesh " << domain << "\n";
	vtkUnsignedCharArray *ghost_zones = vtkUnsignedCharArray::New();
	ghost_zones->SetName("avtGhostZones");
	int ncells = 4;
	ghost_zones->SetNumberOfTuples(ncells);
	unsigned char *gzp = ghost_zones->GetPointer(0);
	for (int i = 0; i < ncells; i++)
		gzp[i] = 0;
	unsigned char val = 0;
	avtGhostData::AddGhostZoneType(val, DUPLICATED_ZONE_INTERNAL_TO_PROBLEM);
	gzp[1] = val;
	gzp[3] = val;

	vtkUnsignedCharArray *ghost_nodes = vtkUnsignedCharArray::New();
	ghost_zones->SetName("avtGhostNodes");
	int npts = 9;
	ghost_nodes->SetNumberOfTuples(npts);
	unsigned char *gnp = ghost_nodes->GetPointer(0);
	for (int i = 0; i < npts; i++)
		gnp[i] = 0;
	unsigned char val2 = 0;
	avtGhostData::AddGhostNodeType(val2, DUPLICATED_NODE);
	gzp[6] = val2;
	gzp[7] = val2;
	gzp[8] = val2;

	if (domain == 0)
	{
		int numNodes = 9;
		points->SetNumberOfPoints(numNodes);
		double * pointPtr = (double *)points->GetVoidPointer(0);
		for (int i = 0; i < 3; i++)
			for (int j = 0; j < 3; j++)
			{

				double x = 0.0 + i * 100;
				double y = 0.0 + j * 65;
				*pointPtr++ = x;
				*pointPtr++ = y;
				*pointPtr++ = 0.0;
			}
		uGrid->SetPoints(points);
		points->Delete();
		uGrid->Allocate(4);


		debug1 << "start creating d1 cells\n";
		vtkIdType verts1[4];
		verts1[0] = 0;
		verts1[1] = 1;
		verts1[2] = 4;
		verts1[3] = 3;
		uGrid->InsertNextCell(VTK_QUAD, 4, verts1);
		vtkIdType verts2[4];
		verts2[0] = 1;
		verts2[1] = 2;
		verts2[2] = 5;
		verts2[3] = 4;
		uGrid->InsertNextCell(VTK_QUAD, 4, verts2);
		vtkIdType verts3[4];
		verts3[0] = 3;
		verts3[1] = 4;
		verts3[2] = 7;
		verts3[3] = 6;
		uGrid->InsertNextCell(VTK_QUAD, 4, verts3);
		vtkIdType verts4[4];
		verts4[0] = 4;
		verts4[1] = 5;
		verts4[2] = 8;
		verts4[3] = 7;
		uGrid->InsertNextCell(VTK_QUAD, 4, verts4);
		debug1 << "inserted d1 cells\n";
		uGrid->GetCellData()->AddArray(ghost_zones);
		uGrid->GetCellData()->AddArray(ghost_nodes);
		debug1 << "d1 ghost added\n";
	}
	else if (domain == 1)
	{
		int numNodes = 9;
		points->SetNumberOfPoints(numNodes);
		double * pointPtr = (double *)points->GetVoidPointer(0);
		for (int i = 0; i < 3; i++)
			for (int j = 0; j < 3; j++)
			{

				double x = 200.0 + i * 100;
				double y = 0.0 + j * 65;
				*pointPtr++ = x;
				*pointPtr++ = y;
				*pointPtr++ = 0.0;
			}
		uGrid->SetPoints(points);
		points->Delete();
		uGrid->Allocate(4);
		debug1 << "start creating d2 cells\n";

		vtkIdType verts1[4];
		verts1[0] = 0;
		verts1[1] = 1;
		verts1[2] = 4;
		verts1[3] = 3;

		uGrid->InsertNextCell(VTK_QUAD, 4, verts1);
		vtkIdType verts2[4];

		verts2[0] = 1;
		verts2[1] = 2;
		verts2[2] = 5;
		verts2[3] = 4;
		uGrid->InsertNextCell(VTK_QUAD, 4, verts2);
		vtkIdType verts3[4];

		verts3[0] = 3;
		verts3[1] = 4;
		verts3[2] = 7;
		verts3[3] = 6;
		uGrid->InsertNextCell(VTK_QUAD, 4, verts3);
		vtkIdType verts4[4];

		verts4[0] = 4;
		verts4[1] = 5;
		verts4[2] = 8;
		verts4[3] = 7;
		uGrid->InsertNextCell(VTK_QUAD, 4, verts4);
		uGrid->GetCellData()->AddArray(ghost_zones);
		uGrid->GetCellData()->AddArray(ghost_nodes);
		debug1 << "d2 ghost added\n";
	}
	else
	{

	}



	return uGrid;
    return m_impl->GetMesh(timestate,domain,this,meshname);
}


// ****************************************************************************
//  Method: avtMDSCHISMFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      timestate  The index of the timestate.  If GetNTimesteps returned
//                 'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: qshu -- generated by xml2avt
//  Creation:   Fri Jul 31 10:54:14 PDT 2020
//
// ****************************************************************************

vtkDataArray *
avtMDSCHISMFileFormat::GetVar(int timestate, int domain, const char *varname)
{
   int ntuples = 9; // this is the number of entries in the variable.
	vtkDoubleArray *rv = vtkDoubleArray::New();
	rv->SetNumberOfTuples(ntuples);
	double * val_arr = new double[ntuples];
	for (int i = 0; i < ntuples; i++)
	{
		double val = i * 0.5;
		val_arr[i] = val;
	}

	if (domain == 0)
	{
		val_arr[2] = val_arr[0];
		val_arr[5] = val_arr[3];
		val_arr[8] = val_arr[6];

	}

	for (int i = 0; i < ntuples; i++)
	{
		rv->SetTuple1(i, val_arr[i]);
	}

	delete val_arr;
	return rv;
   return m_impl->GetVar(timestate,domain,varname);

    //
    // If you have a file format where variables don't apply (for example a
    // strictly polygonal format like the STL (Stereo Lithography) format,
    // then uncomment the code below.
    //
    // EXCEPTION1(InvalidVariableException, varname);
    //

    //
    // If you do have a scalar variable, here is some code that may be helpful.
    //
    // int ntuples = XXX; // this is the number of entries in the variable.
    // vtkFloatArray *rv = vtkFloatArray::New();
    // rv->SetNumberOfTuples(ntuples);
    // for (int i = 0 ; i < ntuples ; i++)
    // {
    //      rv->SetTuple1(i, VAL);  // you must determine value for ith entry.
    // }
    //
    // return rv;
    //
}


// ****************************************************************************
//  Method: avtMDSCHISMFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      timestate  The index of the timestate.  If GetNTimesteps returned
//                 'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: qshu -- generated by xml2avt
//  Creation:   Fri Jul 31 10:54:14 PDT 2020
//
// ****************************************************************************

vtkDataArray *
avtMDSCHISMFileFormat::GetVectorVar(int timestate, int domain,const char *varname)
{
	return NULL;
    return m_impl->GetVectorVar(timestate,domain,varname);
    //
    // If you have a file format where variables don't apply (for example a
    // strictly polygonal format like the STL (Stereo Lithography) format,
    // then uncomment the code below.
    //
    // EXCEPTION1(InvalidVariableException, varname);
    //

    //
    // If you do have a vector variable, here is some code that may be helpful.
    //
    // int ncomps = YYY;  // This is the rank of the vector - typically 2 or 3.
    // int ntuples = XXX; // this is the number of entries in the variable.
    // vtkFloatArray *rv = vtkFloatArray::New();
    // int ucomps = (ncomps == 2 ? 3 : ncomps);
    // rv->SetNumberOfComponents(ucomps);
    // rv->SetNumberOfTuples(ntuples);
    // float *one_entry = new float[ucomps];
    // for (int i = 0 ; i < ntuples ; i++)
    // {
    //      int j;
    //      for (j = 0 ; j < ncomps ; j++)
    //           one_entry[j] = ...
    //      for (j = ncomps ; j < ucomps ; j++)
    //           one_entry[j] = 0.;
    //      rv->SetTuple(i, one_entry); 
    // }
    //
    // delete [] one_entry;
    // return rv;
    //
}

void avtMDSCHISMFileFormat::addMeshToMetaData(avtDatabaseMetaData * a_metaData,
	const std::string & a_mesh_name,
	const avtMeshType & a_mt,
	double           *  a_extents,
	const int        &  a_nblocks,
	const int        &  a_block_origin,
	const int        &  a_spatial_dimension,
	const int        &  a_topological_dimension)
{
	AddMeshToMetaData(a_metaData,
		a_mesh_name,
		a_mt,
		a_extents,
		a_nblocks,
		a_block_origin,
		a_spatial_dimension,
		a_topological_dimension);

}


void   avtMDSCHISMFileFormat::addScalarVarToMetaData(avtDatabaseMetaData * a_metaData,
	const std::string & a_label,
	const std::string & a_mesh,
	const avtCentering& a_center)
{
	AddScalarVarToMetaData(a_metaData, a_label, a_mesh, a_center);
}

void   avtMDSCHISMFileFormat::addVectorVarToMetaData(avtDatabaseMetaData * a_metaData,
	const std::string &  a_varLabel,
	const std::string &  a_mesh,
	const avtCentering&  a_center,
	const int &          a_comps)
{

	AddVectorVarToMetaData(a_metaData, a_varLabel, a_mesh, a_center, a_comps);
}

avtVariableCache * avtMDSCHISMFileFormat::get_cache()
{
	return this->cache;
}


